=== Mussse97/Webb3-Alla-labbar/L5/L5b/XmlFiler/games.dtd
<!-- 
gamesobjekt
   developers riot eller fromsoftware
      games
	    game
		playerbase
	description   

          
-->   

<!ELEMENT games_objects (developer+)>
	<!ELEMENT developer (games, description*)>
			<!ATTLIST developer type (riot|fromsoftware) #REQUIRED>
		<!ELEMENT games (game, playerbase, url)>
			<!ELEMENT game (#PCDATA)>
			<!ELEMENT playerbase (#PCDATA)>
			<!ELEMENT url (#PCDATA)>
		<!ELEMENT description (#PCDATA)>

=== Mussse97/Webb3-Alla-labbar/L5/L5b/XmlFiler/games1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE games_objects SYSTEM "games.dtd">

<games_objects>
    <developer type="riot">
        <games>
            <game>league of legends</game>
            <playerbase>I 2020 har det räknats upp till 100 miljoner konton som skapats och det är över 500.000 som spelar dagligen.</playerbase>
            <url>https://www.leagueoflegends.com/en-gb/how-to-play/</url>
        </games>
        <description>League of Legends är ett lagbaserat multiplayer spel där skicklighet och lagarbete är viktigt för att vinna.</description>    
    </developer>

    <developer type="fromsoftware">
        <games>
            <game>Darksouls 3</game>
            <playerbase>Darksould 3 har sålt över 100 miljoner kopior och är en av dom mest spelade singelplayer spel på steam.</playerbase>
            <url>https://sv.wikipedia.org/wiki/Dark_Souls_III</url>
        </games>
        <description>Dark souls spelen är vad fromsoftware är kännda för. Det är spel som också är kända för att vara svårare än de traditionella singelplayer spelen som finns. Man kan inte välja svårighetsgrad vilket betyder att man måste anpassa sig till den svåra miljön.</description>    
    </developer>
</games_objects>

=== Mussse97/Webb3-Alla-labbar/L5/L5b/XmlFiler/games3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE games_objects SYSTEM "games.dtd">

<games_objects>
    <developer type="riot">
        <games>
            <game>Teamfight tactiks</game>
            <playerbase>Teamfight tacktiks har sätt upp till 128 miljoner spelare i månaden och 10 miljoner dagligen</playerbase>
            <url>https://en.wikipedia.org/wiki/Teamfight_Tactics</url>
        </games>  
    </developer>

    <developer type="fromsoftware">
        <games>
          <game>Elden ring</game>
            <playerbase>Elden ring är inte ute än och därför finns det ingen information om antal spelare.</playerbase>
            <url>https://en.wikipedia.org/wiki/Elden_Ring</url>
        </games>  
    </developer>
</games_objects>

=== Mussse97/Webb3-Alla-labbar/L5/L5b/XmlFiler/games2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE games_objects SYSTEM "games.dtd">

<games_objects>
    <developer type="riot">
        <games>
            <game>Valorant</game>
            <playerbase>Valorant har i genomsnitt 13,863,342 spelare i månaden</playerbase>
            <url>https://sv.wikipedia.org/wiki/Valorant</url>
        </games>
        <description>Valorant ett first person shooter spel som liknar kännda produkter som csgo. Valorant är det nyaste spelet från Riot games.</description>    
    </developer>

    <developer type="fromsoftware">
        <games>
            <game>Sekiro:shadows die twice</game>
            <playerbase>Sekiro solde över två miljoner kopior under 10 dagar när spelet först släpptes.</playerbase>
            <url>https://en.wikipedia.org/wiki/Sekiro:_Shadows_Die_Twice</url>
        </games>
        <description>Sekiro liknar dark souls spelen på många sätt då fromsoftware gillar att skapa samma typ av spel. Allt från svårighetsgraden till berättelsen i spelen liknar varandra.</description>    
    </developer>
</games_objects>
